@startuml

class DrawingEditor{
    + export_to_xml():void
}


class XML_ADAPTEE{
    export_to_xml(editor,xml_data):void   
    save_different_format(filename, data):void
}



class XMLAdapter{
    convert_to_xml(input_format):void
}
   
DrawingEditor -- XMLAdapter: contains 
XMLAdapter "1" --|> "1" XML_ADAPTEE
    
@enduml