@startuml

Class Line{
    + id:int
    + x1:Float
    + y1:Float
    + x2:Float
    + y2:Float
    + color:String
    + dash_offset:Float
    + draw():void
    + set_id():void
    + is_clicked(x,y):void
    + move(dx,dy):void
    + edit():void
    + set_color(color):void
    + show_on_select():void
    + ungroup():void
    + delete():void
    + move_dash():void
    + check_in_area(start_x,start_y,x,y):bool
    + get_code():String
    + draw_item():void
    + copy():Line
}

Class Rectangle{
    + id:int
    + x1:Float
    + y1:Float
    + x2:Float
    + y2:Float
    + color:String
    + corner_style:String
    + dash_offset:Float
    + draw(canvas):void
    + set_id(id):void
    + is_clicked(x,y):void
    + move(dx,dy):void
    + edit():void
    + set_color(color):void
    + set_corner(corner):void
    + show_on_select():void
    + ungroup():void
    + delete():void
    + move_dash():void
    + check_in_area(start_x,start_y,x,y):bool
    + get_code():String
    + draw_item():void
    + copy():Rectangle
}

Class Group{
    + List<DrawingObjects>:List
    + add_object(object):void
    + draw(canvas):void
    + is_clicked(x,y):void
    + delete():void
    + copy():void
    + move():void
    + show_on_select():void
    + ungroup():void
    + ungroup_all():void
    + delete():void
    + check_in_area():bool
    + get_code():String
    + draw_item():void
    + copy():Group
}
  
class DrawingObject{
    + is_clicked(x, y):void
    + delete():void
    + copy():void
    + move(dx, dy):void
    + show_on_select():void
    + delete():void
    + check_in_area(start_x,start_y, x, y):void
    + get_code():void
    + show_edit_menu():void
    + draw_item():void
    + copy():
}

Group "1" *-- "0..*" DrawingObject : has
DrawingObject <|-- Line
DrawingObject <|-- Rectangle
DrawingObject <|-- Group

@enduml